spring.application.name=medicamentos-api

# Server Configuration
server.servlet.context-path=/
server.port=${PORT:8080}

# Database Configuration
spring.datasource.url=jdbc:h2:file:./data/hospitaldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=false

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Logging
logging.level.root=INFO
logging.level.com.petcc_enfermagem=DEBUG